# -*- coding: utf-8 -*-
"""evblast_model_deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UZCm4EFSKexDqZynJScoMdJ2RY7E9o8w
"""


import numpy as np
import joblib
import streamlit as st

model = joblib.load('model.pkl')

st.set_page_config(page_title='Battery Type Classifier',layout='centered')
st.title('Battery Type Classification app')
st.write("predict whether Lead-Acid or Lithium-Ion ")


Poor_Cell_Design = st.number_input('Poor Cell Design',value=None)
External_Abuse	= st.number_input('External Abuse', value=None)
Poor_Battery_Design	= st.number_input('Poor Battery Design', value=None)
Short_Circuits	= st.number_input('Short Circuits', value=None)
Temperature	= st.number_input('Temperature', value=None)
Overcharge_Overdischarge	= st.number_input('Overcharge/Overdischarge', value=None)
Battery_Maintenance	= st.number_input('Battery Maintenance', value=None)
Battery_Health = st.number_input('Battery Health', value=None)

if st.button('Predict'):
  input_data = np.array([[
      Poor_Cell_Design,
      External_Abuse,
      Poor_Battery_Design,
      Short_Circuits,
      Temperature,
      Overcharge_Overdischarge,
      Battery_Maintenance,
      Battery_Health
  ]])
  prediction = model.predict(input_data) [0]
  if prediction == 1:
    st.error('Lead-Acid')
  else:
    st.success('Lithium-Ion')
